config:
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  import_variables:
  - variables.d/myvars.yaml

options:
  confpath: ~/.dotfiles
  tmpdir: ~/dotdrop_temp
dotfiles:
  f_gitconfig:
    src: home/jacoba/.gitconfig
    dst: /home/jacoba/.gitconfig
  d_scripts:
    src: scripts
    dst: ~/scripts
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
profiles:
  jacobaarch:
    dotfiles:
    - f_gitconfig
    - d_scripts
    - d_nvim
    - f_tmux.conf
    - f_tmux.conf.local
    - d_alacritty
