config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  import_variables:
  - variables.d/myvars.yaml

options:
  confpath: ~/.dotfiles
  tmpdir: ~/dotdrop_temp
dotfiles:
  f_zshrc:
    src: home/jacoba/.zshrc
    dst: /home/jacoba/.zshrc
  f_gitconfig:
    src: home/jacoba/.gitconfig
    dst: /home/jacoba/.gitconfig
  d_screenlayout:
    src: home/jacoba/.screenlayout
    dst: /home/jacoba/.screenlayout
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_scripts:
    src: scripts
    dst: ~/scripts
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_default:
    src: config/BraveSoftware/Brave-Browser/Default
    dst: ~/.config/BraveSoftware/Brave-Browser/Default
    chmod: '700'
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_gitconfig
    - d_screenlayout
    - d_bspwm
    - d_scripts
    - d_nvim
    - f_tmux.conf
    - f_tmux.conf.local
    - d_alacritty
    - d_default
