return {

  -- { "typescript-language-server", enabled = false },
  -- {
  --     "pmizio/typescript-tools.nvim",
  --     dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  --     event = { "BufRead", "BufNewFile" },
  --
  --     config = function()
  --         require("typescript-tools").setup({
  --             root_dir = require("lspconfig").util.root_pattern(".git"),
  --             settings = {
  --
  --                 tsserver_max_memory = "1024",
  --
  --                 tsserver_file_preferences = {
  --                     includeInlayParameterNameHints = "literal",
  --                     includeInlayParameterNameHintsWhenArgumentMatchesName = false,
  --                     includeInlayFunctionParameterTypeHints = true,
  --                     includeInlayVariableTypeHints = true,
  --                     includeInlayPropertyDeclarationTypeHints = true,
  --                     includeInlayFunctionLikeReturnTypeHints = true,
  --                     includeInlayEnumMemberValueHints = true,
  --                     separate_diagnostic_server = false,
  --                     organizeImportsIgnoreCase = true,
  --                     importModuleSpecifierPreference = "minimal",
  --                     importModuleSpecifierEnding = "minimal",
  --                     includeInlayVariableTypeHintsWhenTypeMatchesName = false,
  --
  --                     includeCompletionsForModuleExports = true,
  --                     jsxAttributeCompletionStyle = "double",
  --                 },
  --                 tsserver_format_options = {
  --                     quotePreference = "double",
  --                     allowIncompleteCompletions = true,
  --                 },
  --             },
  --         })
  --         local autocmd = vim.api.nvim_create_autocmd
  --         autocmd("BufWritePre", {
  --             pattern = "*.ts,*.tsx,*.jsx,*.js",
  --             callback = function(_)
  --                 vim.cmd("TSToolsAddMissingImports sync")
  --                 vim.cmd("TSToolsRemoveUnused sync")
  --             end,
  --         })
  --     end,
  -- },
}
