return {

    -- {
    --     "neovim/nvim-lspconfig",
    --     opts = {
    --         -- make sure mason installs the server
    --         servers = {
    --             ---@type lspconfig.options.tsserver
    --             tsserver = {
    --
    --                 keys = {
    --                     {
    --                         "<leader>co",
    --                         function()
    --                             vim.lsp.buf.code_action({
    --                                 apply = true,
    --                                 context = {
    --                                     only = { "source.fixAll" },
    --                                     diagnostics = {},
    --                                 },
    --                             })
    --                         end,
    --                         desc = "Organize Imports",
    --                     },
    --                 },
    --                 ---@diagnostic disable-next-line: missing-fields
    --                 settings = {
    --                     completions = {
    --                         completeFunctionCalls = true,
    --                     },
    --                 },
    --             },
    --         },
    --     },
    -- },
}
