#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#	gh0stzk - https://github.com/gh0stzk/dotfiles

import = [
  "~/.config/alacritty/rice-colors.toml",
  "~/.config/alacritty/fonts.toml",
]

live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15
[env]
TERM = "xterm-256color"
[cursor.style]
blinking = "On"
shape = "Block"
[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.96
dynamic_padding = true

[window.padding]
x = 16
y = 16

[scrolling]
history = 100000
multiplier = 3
