#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	Script to control prefered apps to launch for all themes
# 	Author: z0mbi3
#	url: https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--menu)
	rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
	;;
--rice)
	RiceSelector
	;;
--terminal)
	if bspc query -N -n .focused >/dev/null; then
		alacritty
	else
		alacritty --class fullscreen
	fi
	;;
--floating)
	alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90
	;;
--update)
	alacritty --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
	;;
--checkupdates)
	alacritty --hold --class Updating,Updating -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
	;;
--ranger)
	alacritty --class FloaTerm,FloaTerm -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
	;;
--monitor)
	source ~/scripts/two_monitors.sh
	;;
--nvim)
	alacritty -e nvim
	;;
# Apps
--browser)
	google-chrome-stable
	;;
--editor)
	nvim
	;;
*)
	echo "Invalid Option"
	;;
esac
